### ISSUE TITLE
Failed to write register

### ISSUE THREAD

**Issue by wfarah** [realtimeradio/ata_snap#40]
This is the error, @jack-h 

```
Traceback (most recent call last):
  File "/home/sonata/dev/ATA-Utils/pythonLibs/SNAPobs/snap_hpguppi/scripts/configure_antenna_streams.py", line 297, in <module>
    raise e
  File "/home/sonata/dev/ATA-Utils/pythonLibs/SNAPobs/snap_hpguppi/scripts/configure_antenna_streams.py", line 283, in <module>
    rfsoc_feng_init.run(
  File "/home/sonata/dev/ata_snap/sw/ata_snap/scripts/rfsoc_feng_init.py", line 147, in run
    output = feng.select_output_channels(start_chan, n_chans, feng_dests, n_interfaces=n_interfaces, dest_ports=dest_port, nchans_per_packet_limit=chans_per_packet_limit)
  File "/home/sonata/miniconda3/envs/rfsoc8bit/lib/python3.8/site-packages/ata_snap/ata_rfsoc_fengine.py", line 713, in select_output_channels
    self._reorder_channels(chan_reorder_map)
  File "/home/sonata/miniconda3/envs/rfsoc8bit/lib/python3.8/site-packages/ata_snap/ata_rfsoc_fengine.py", line 852, in _reorder_channels
    self.fpga.write(reg, out_bytes[4*i:4*(i+1)], offset=4*i + 2*offset_words)
  File "/home/sonata/miniconda3/envs/rfsoc8bit/lib/python3.8/site-packages/casperfpga/casperfpga.py", line 527, in write
    self.blindwrite(device_name, data, offset)
  File "/home/sonata/miniconda3/envs/rfsoc8bit/lib/python3.8/site-packages/casperfpga/casperfpga.py", line 277, in blindwrite
    return self.transport.blindwrite(device_name, data_byte_swapped, offset, **kwargs)
  File "/home/sonata/miniconda3/envs/rfsoc8bit/lib/python3.8/site-packages/casperfpga/transport_katcp.py", line 414, in blindwrite
    self.katcprequest(name='write', request_timeout=self._timeout,
  File "/home/sonata/miniconda3/envs/rfsoc8bit/lib/python3.8/site-packages/casperfpga/transport_katcp.py", line 280, in katcprequest
    raise KatcpRequestFail(
casperfpga.transport_katcp.KatcpRequestFail: Request write on host rfsoc1-ctrl-1 failed.
	Request: ?write chan_reorder0_reorder2_map 0 XX\0
	Reply: !write fail
```

**Comment by jack-h** [comment]
Turns out this needed a firmware fix. Recompiling now
